### ISSUE TITLE
Refactor: refactor `changeProperty` and delete `changeStyle`

### ISSUE THREAD

**Issue by sheepbox8646** [dromara/newcar#43]
In most of case, you can use `changeProperty` API to custom your attributes animation, but in recent using, i find many bug and unexpected points.

## Bugs

If you use `move` animation and only provide a parameter `to` (like following codes, and the origin of `move` are also `changeProperty` without from and to), the animation will be loaded no longer correct, the time will get into wrong.

```typescript
circle.animate(move, 0, 30, {
  to: [400, 400] // The animation will loaded wrong duration but it will not throw any error
})
```

## Features

Usage
```typescript
changeProperty('style.xxx', 0, 100)
changeProperty(['from[0]', 'to[0]'], [111, 222], [222, 333])
changeProperty(['style.attr1', 'attr2'], [0, 0], [100, 100])
```

Usage On Widget
```typescript
circle.animate(changeProperty<Circle>(['x', 'style.x']), 0, 30, {
  to: [100, 200] // You can doesn't provide the parameter `from`, but if you want, that is allowed ^_^
})
```

And if `changeProperty` support like `style.xxx` grammar, `changeStyle` is no longer needed.

Who can implement this issue? Please comment under this issue and I'll assign to you to finish this work.

**Comment by wgxh-cli** [comment]
Can you give a detailed description for this issue? Such as a complete example where bug occurs :)

**Comment by wgxh-cli** [comment]
**BUG LOCATED**: The unit system just added, who set `elapsed` wrongly in `app.ts:121`, caused this issue. I'll consider replace the unit system with a new one.

**Comment by wgxh-cli** [comment]
Feature Request:
```ts
/// move.ts
export const move = changeProperty(['x', 'y'])
/// myOwnAnim.ts
// `override` method aims to override the `defaultFrom`, `defaultTo` and `by`
// which is already determined in original declaration
widget.animate(move.override({ to: [1000, 500] }))
```

**Comment by sheepbox8646** [comment]
okay
