### ISSUE TITLE
Consider add `fps` again

### ISSUE THREAD

**Issue by wgxh-cli** [dromara/newcar#45]
Unit system cannot hold without a precise definition of `fps`, otherwise, one shall be confused with how many frames to advance within a so-called "unit".

**Comment by sheepbox8646** [comment]
You should do this under the rule that don't make breaking change! Please add back `unit`

**Comment by wgxh-cli** [comment]
**Breaking changes** should be allowed when needed

Generally speaking, When playing animations, `elapsed` should be advanced by **1** each time called `update`, rather than set directly by physical time elapsed.

Current implementation take the `fps` as default as 1000 per second, that is 1 per millisecond, but actually not every frame take time exactly as 1 milisecond
